apiVersion: v1
kind: ConfigMap
metadata:
  name: lacework-config
data:
  config.json: |
    {"tokens":{"AccessToken":"e73f8cbffb37a5f1d86314f6a0df7caba508c07a7b47a28e298da4e5"}, "tags":{"Env":"k8s"}, "serverurl":"https://api.lacework.net"}
  syscall_config.yaml: |
    ""

